set(FIND_STATICLIB_PATHS ~/Projects/Labs/libs/static)

find_path(STATICLIB_INCLUDE_DIR utils.h PATH_SUFFIXES include PATHS ${FIND_STATICUTILS_PATHS})

find_library(STATICLIB_LIBRARY NAMES libStaticUtils.a PATH_SUFFIXES lib PATHS ${FIND_STATICUTILS_PATHS})